config/routes.rb
Rails.application.routes.draw do
  resources :reviews, only: [:create]
  resources :genres, except: :delete
  resources :bands, except: :delete
  resources :musicians, except: :delete

  get "/login", to: "sessions#new", as: 'login'
  post "/login", to: "sessions#create"
  delete "/logout", to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :musician_bands
  has_many :musicians, through: :musician_bands
  has_many :reviews

  validates :band_name, presence: true
  validates :band_name, uniqueness: true

  def average_rating
    rating_array = self.reviews.map do |review|
      review.stars
    end
    rating_array.inject(:+)/rating_array.length
  end

  def musicians_not_in_band
    bands_musicians = self.musicians
    all_musicians = Musician.all
      all_musicians.select do |musician|
        bands_musicians.exclude?(musician)
      end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_musicians
  has_many :musicians, through: :genre_musicians

  validates :genre_name, presence: true
  validates :genre_name, uniqueness: true
  validates :description, presence: true
  validates :description, length: {maximum: 1000}
end

app/models/genre_musician.rb
class GenreMusician < ApplicationRecord
  belongs_to :genre
  belongs_to :musician
end

app/models/musician.rb
class Musician < ApplicationRecord
  has_many :genre_musicians
  has_many :musician_bands
  has_many :genres, through: :genre_musicians
  has_many :bands, through: :musician_bands

  validates :name, presence: true
  validates :instrument, presence: true
  validates :time_for_music, presence: true
  validates :time_for_music, numericality: { :only_integer => true, :greater_than_or_equal_to => 0 }

  def instrument_capitalize
    instrument = self.instrument.split.map(&:capitalize).join(' ')
    self.instrument = instrument
  end

  def self.genre_type(genre_name)
    Genre.find_by(genre_name: genre_name).musicians
  end
end

app/models/musician_band.rb
class MusicianBand < ApplicationRecord
  belongs_to :musician 
  belongs_to :band
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :band

  validates :stars, presence: true
  validates :stars, numericality: true
  validates :stars, numericality: { :only_integer => false, :greater_than_or_equal_to => 0 }
  validates :stars, numericality: { :only_integer => false, :less_than_or_equal_to => 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorized
  helper_method :current_musician

  def current_musician
    Musician.find_by(id: session[:musician_id])
  end

  def logged_in?
    !!current_musician
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    @band = Band.new
  end

  def create
    @band = Band.create(band_params)
    if @band.valid?
      redirect_to band_path(@band)
    else
      @errors = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @musician = Musician.find(session[:musician_id])
    @band = Band.find(params[:id])
    @addable_musicians = Musician.all

  end

  def update
    @band = Band.find(params[:id])
    @band.update(band_params)
    if @band.valid?
      redirect_to band_path(@band)
    else
      @errors = @band.errors.full_messages
      render :edit
    end
  end

  def show
    @band = Band.find(params[:id])
    @review = Review.new(band_id: params[:id])
  end

  def index
    @bands = Band.all
  end

  private

  def band_params
    params.require(:band).permit(:band_name, :tours, :logo, :musician_ids => [])
  end
end

app/controllers/genre_musicians_controller.rb
class GenreMusiciansController < ApplicationController
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.create(genre_params)
    if @genre.valid?
      redirect_to genre_path(@genre)
    else
      @errors = @genre.errors.full_messages
      render :new
    end
  end

  def index
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    if @genre.valid?
      redirect_to genre_path(@genre)
    else
      @errors = @genre.errors.full_messages
      render :edit
    end
  end

  def show
    @genre = Genre.find(params[:id])
  end



  private

  def genre_params
    params.require(:genre).permit(:genre_name, :description)
  end
end

app/controllers/musician_bands_controller.rb
class MusicianBandsController < ApplicationController
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def new
    @musician = Musician.new
  end

  def create
    @musician = Musician.new(musician_params)
    if @musician.valid?
      @musician.instrument_capitalize
      @musician.save
      session[:musician_id] = @musician.id
      redirect_to musician_path(@musician)
    else
      @errors = @musician.errors.full_messages
      render :new
    end
  end

  def edit
    @musician = Musician.find(params[:id])
    unless @musician.id == session[:musician_id]
      redirect_to musician_path(@musician)
    end
  end

  def update
    @musician = Musician.find(params[:id])
    @musician.update(musician_params)
    if @musician.valid?
      @musician.instrument_capitalize
      @musician.save
      redirect_to musician_path(@musician)
    else
      @errors = @musician.errors.full_messages
      render :edit
    end
  end

  def show
    @musician = Musician.find(params[:id])
  end

  def destroy
    @musician = Musician.find(session[:musician_id])
  end

  def index
    if params[:instrument_search] && params[:genre][:genre_search] == ""
      @musicians = Musician.where('instrument Like ?', "%#{params[:instrument_search]}")
    elsif params[:instrument_search] == "" && params[:genre][:genre_search]
      @musicians = Musician.genre_type(params[:genre][:genre_search])
    elsif params[:instrument_search] && params[:genre][:genre_search]
      @musicians = Musician.genre_type(params[:genre][:genre_search]).where('instrument Like ?', "%#{params[:instrument_search]}")
    else

      @musicians = Musician.all
    end
  end


  private

  def musician_params
    params.require(:musician).permit(:name, :instrument, :description, :time_for_music, :instrument_search, :genre_search, :genre_ids => [])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create

    @review = Review.create(review_params)
    if @review.valid?
      redirect_to band_path(@review.band)
    else

      flash[:error] = @review.errors.full_messages
      redirect_to band_path(@review.band)
    end
  end

  private

  def review_params
    params.require(:review).permit(:band_id, :comment, :stars)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
  end

  def create
    @musician = Musician.find_by(name: params[:username])
    if @musician
      session[:musician_id] = @musician.id
      redirect_to musician_path(@musician)
    else
      flash[:notice] = "No Username"
      redirect_to login_path
    end
  end

  def destroy
    session.delete :musician_id
    redirect_to login_path
  end

  private
  def session_params
    params.require(:session).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/genre_musicians_helper.rb
module GenreMusiciansHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/musician_bands_helper.rb
module MusicianBandsHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/bands/edit.erb
<% if @errors %>
  <div class="container">
    <div class="text-white bg-danger mb-3" >
      <ul>
        <% @errors.each do |error| %>
          <li><h1><%= error %></h1><br></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<% if @band.musicians.include?(current_musician) %>
  <div class="container">
    <div class="card bg-dark">
      <div class="p-3 mb-2 bg-dark text-white">
        <%= form_for @band do |f| %>
          <div class="card-header"> <h3> <%= f.label :band_name %></h3>
            <%= f.text_field :band_name, class:"form-control"%> </div>
            <%= f.label :tours %>
            <%= f.check_box :tours %>
              <div class="card bg-dark">
                <div class="card-header">
                  <h6> Musicians</h6>
                </div>
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Musicians for ya band
                  </button>
                  <div class="dropdown-menu btn btn-secondary btn-sm" aria-labelledby="dropdownMenuButton">
                    <%= f.collection_check_boxes(:musician_ids, @addable_musicians, :id, :name) do |musician|%>
                      <%= musician.label class: 'dropdown-item' do %>
                        <%= musician.check_box + ' ' + musician.text%>
                      <% end %>
                    <% end %>
                  </div>
                </div><br>
                <%= f.submit "Make Ya Band", class: "btn btn-secondary btn-sm"%>
            <% end %>
                </div>
        </div>
      </div>
    </div>
<% end %>

app/views/bands/index.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="row">
      <div class="container scroll">
        <div class="card bg-dark" >
          <div class="card-header">
            <h3>Bands</h3>
            <p>average rating</p>
            <div class="right">
              <a href="/bands/new">Make ya own Band!!!!</a>
            </div>
          </div>
            <div class="p-3 mb-2 bg-dark text-white">
              <ul>
                <%  @bands.each do |band|%>
                  <li><%= link_to band.band_name, band_path(band) %>
                        <%if band.reviews.count > 0  %>
                          <%= band.average_rating.round(1) %>
                        <% else %>
                          <a><%= "N/A" %></a>
                        <% end %>
                        <% if band.musicians.include?(current_musician) %>
                          <%= link_to 'Edit', edit_band_path(band), class: "btn btn-secondary btn-sm" %>
                        <% end %>
                    <% end %></li>
              </ul>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/bands/new.erb
<% if @errors %>
<div class="container">

<div class="text-white bg-danger mb-3" >
  <ul>
  <% @errors.each do |error| %>
    <li><h1><%= error %></h1><br></li>
  <% end %>
</ul>
  </div>
</div>
<% end %>

<div class="container">
  <div class="card bg-dark">
    <div class="p-3 mb-2 bg-dark text-white">
      <%= form_for @band do |f| %>
        <div class="card-header"> <h3> <%= f.label :band_name %></h3>
          <%= f.text_field :band_name, class:"form-control" %>
        </div>
        <%= f.label :tours %>
        <%= f.check_box :tours %>

        <div class="card bg-dark">
        <div class="card-header">
            <h6> Musicians</h6>
        </div>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Musicians for ya band
            </button>
            <div class="dropdown-menu btn btn-secondary btn-sm" aria-labelledby="dropdownMenuButton">
                <%= f.collection_check_boxes(:musician_ids, Musician.all, :id, :name) do |musician|%>
                    <%= musician.label class: 'dropdown-item' do %>
                        <%= musician.check_box + ' ' + musician.text %>
                    <% end %>
                <% end %>
            </div>
        </div><br>
        <%= f.submit "Make Ya Band", class: "btn btn-secondary btn-sm" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bands/show.erb
<div class="container">
  <div class="card bg-dark">
    <div class="p-3 mb-2 bg-dark text-white">
      <div class="card-header"> <h3><%= @band.band_name %></h3> </div>
        <%if @band.tours %>
              <p>  <%= "We Tour" %> </p>
        <% end %>
        <%= @band.logo %>
        <div class="card bg-dark">
          <div class="card-header">
            <h6> Musicians</h6>
          </div>
          <% @band.musicians.each do |musician| %>
              <%= link_to musician.name + " - #{musician.instrument}" , musician_path(musician) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


<% if flash[:error] %>
  <div class="container">
    <div class="text-white bg-danger mb-3" >
      <ul>
        <% flash[:error].each do |error| %>
          <li><h1><%= error %></h1><br></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="card bg-dark">
    <div class="p-3 mb-2 bg-dark text-white">
      <h3>Write a Review</h3>
      <%= form_for @review do |f| %>
        <%=f.hidden_field :band_id, band_id: @band.id%>
        <a>Number of Stars</a>
        <%= f.number_field :stars, :step => 0.5, class:"form-control" %>
        <a>Comment</a>
        <%= f.text_field :comment, class:"form-control" %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">

  <div class="card bg-dark">
    <div class="p-3 mb-2 bg-dark text-white">
      <h3>Comments</h3>

      <div class="shorter scroll">
        <% @band.reviews.each do |review| %>
          <div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">
            <div class="p-3 mb-2 bg-dark text-white">
            <%= review.stars %><br>
            <%= review.comment %><br>
            </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/genres/edit.erb
<% if @errors %>
<div class="container">

<div class="text-white bg-danger mb-3" >
  <ul>
  <% @errors.each do |error| %>
    <li><h1><%= error %></h1><br></li>
  <% end %>
</ul>
  </div>
</div>
<% end %>

<div class="container">
<div class="card bg-dark">
  <div class="p-3 mb-2 text-white">
      <%= form_for @genre do |f| %>
        <div class="card-header"> <h3><%= f.label :genre_name %>
          <%= f.text_field :genre_name, class:"form-control" %>
        </h3> </div>
        <p><%= f.label :description %>
        <%= f.text_area :description, class:"form-control" %>
        </p>
        <%= f.submit "Save Edit", class: "btn btn-secondary btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/genres/index.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <div class="row">

      <div class="container">
        <div class="card bg-dark" >
          <div class="card-header"><h3>Genres</h3></div>

            <div class="p-3 mb-2 bg-dark text-white scroll">
              <ul>

                <%  @genres.each do |genre|%>
                  <li><%= link_to genre.genre_name, genre_path(genre) %><br></li>
                <% end %>
              </ul>
              <a href="/genres/new">Don't See the Genre? Add it here</a>
            </div>
          </div>
        </div>
      </div>

  </body>
</html>

app/views/genres/new.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <% if @errors %>
    <div class="container">

    <div class="text-white bg-danger mb-3" >
      <ul>
      <% @errors.each do |error| %>
        <li><h1><%= error %></h1><br></li>
      <% end %>
    </ul>
      </div>
    </div>
    <% end %>

  <div class="container">
    <div class="card bg-dark">
      <div class="p-3 mb-2 text-white">
          <%= form_for @genre do |f| %>
            <div class="card-header"> <h3><%= f.label :genre_name %>
              <%= f.text_field :genre_name, class:"form-control" %>
            </h3> </div>
            <p><%= f.label :description %>
            <%= f.text_area :description, class:"form-control"%>
            </p>
            <%= f.submit "Make the Genre", class: "btn btn-secondary btn-sm" %>
          <% end %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/genres/show.erb
<div class="container">

  <div class="card bg-dark">
    <div class="p-3 mb-2 bg-dark text-white">

      <div class="card-header">
        <h3> <%= @genre.genre_name %>  </h3>
        <a>  <%= link_to "Edit", edit_genre_path(@genre),class: "btn btn-secondary btn-sm" %> </a>

      </div>

        <p><%= @genre.description %></p>


      </div>
    </div>
  </div>

app/views/musicians/edit.erb
<% if @errors %>
<div class="container">

<div class="text-white bg-danger mb-3" >
  <ul>
  <% @errors.each do |error| %>
    <li><h1><%= error %></h1><br></li>
  <% end %>
</ul>
  </div>
</div>
<% end %>

<div class="container">
  <div class="card bg-dark">
    <div class="p-3 mb-2 bg-dark text-white">
      <%= form_for @musician do |f| %>
        <div class="card-header"> <h3><%= f.label :name %>
        <%= f.text_field :name, class:"form-control" %></h3></div>
        <p><%= f.label :instrument %>
        <%= f.text_field :instrument, class:"form-control" %></p>
        <p><%= f.label :description %>
        <%= f.text_area :description, class:"form-control" %></p>
        <p>Hours per Week for music
        <%= f.number_field :time_for_music, class:"form-control" %></p>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Genres you play
          </button>
          <div class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuButton">
            <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :genre_name) do |genre|%>
              <%= genre.label class: 'dropdown-item bg-dark' do %>
               <%= genre.check_box + ' ' + genre.text%>
              <% end %>
            <% end %>
          </div>
        </div><br>
        <%= f.submit "Submit", class: "btn btn-secondary btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/musicians/index.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>


  <div class="container">
    <div class="card bg-dark">
      <div class="p-3 mb-2 bg-dark text-white">
        <div class="search">
          <h3>Search by</h3>
          <%= form_tag(musicians_path, method: :get) do %>
          <a> Instrument <%= text_field_tag :instrument_search, '', class:"form-control"%></a>
          <a> Genre <%= select :genre, :genre_search, Genre.all.collect {|p| [ p.genre_name]}, {include_blank: true}%></a>
          <%= submit_tag 'Search', class: "btn btn-secondary btn-sm"  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <!-- <div class="moved-right"> -->
    <div class="container">


    <div class="col-6 scroll">

      <div class="card bg-dark" >
        <div class="card-header"><h3>Musicians</h3></div>

          <div class="p-3 mb-2 bg-dark text-white">

            <ul>
              <% @musicians.each do |musician| %>
                <li><%= link_to musician.name, musician_path(musician) %><br></li>
              <% end %><br>
            </ul>
          </div>

        </div>
      </div>
    </div>





  </body>
</html>

app/views/musicians/new.erb
<% if @errors %>
<div class="container">

<div class="text-white bg-danger mb-3" >
  <ul>
  <% @errors.each do |error| %>
    <li><h1><%= error %></h1><br></li>
  <% end %>
</ul>
  </div>
</div>
<% end %>

<div class="container">
  <div class="card bg-dark">
    <div class="p-3 mb-2 bg-dark text-white">
      <%= form_for @musician do |f| %>
        <div class="card-header"> <h3><%= f.label :name %>
        <%= f.text_field :name, class:"form-control" %></h3></div>
        <p><%= f.label :instrument %>
        <%= f.text_field :instrument, class:"form-control" %></p>
        <p><%= f.label :description %>
        <%= f.text_area :description, class:"form-control" %></p>
        <p>Hours per Week for music
        <%= f.number_field :time_for_music, class:"form-control" %></p>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Genres you play
          </button>
          <div class="dropdown-menu btn btn-secondary btn-sm" aria-labelledby="dropdownMenuButton">
            <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :genre_name) do |genre|%>
              <%= genre.label class: 'dropdown-item btn btn-secondary btn-sm' do %>
               <%= genre.check_box + ' ' + genre.text%>
              <% end %>
            <% end %>
          </div>
        </div><br>
        <%= f.submit "Submit", class: "btn btn-secondary btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/musicians/show.erb
<div class="container">

  <div class="card bg-dark">
    <div class="p-3 mb-2 bg-dark text-white">

      <div class="card-header"><h3><%= @musician.name %> </h3>
        <% if @musician.id == session[:musician_id] %>
          <a>   <%= link_to "Edit", edit_musician_path(@musician),class: "btn btn-secondary btn-sm" %> </a>
        <% end %>
      </div>

        <p>Plays: <%= @musician.instrument %></p>

        <p>Description: <%= @musician.description %></p>

        <p>Able to devote <%= @musician.time_for_music %> hours a week for music</p>
        <div class="card-header">
          <h6>Genres played</h6>
        </div>
        <ul>
          <% @musician.genres.each do |genre| %>
            <li><%=link_to genre.genre_name, genre_path(genre)%></li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>